// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinanceTracker.Data;

#nullable disable

namespace PersonalFinanceTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425192041_LocalizeCategorySeed")]
    partial class LocalizeCategorySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PersonalFinanceTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4CAF50",
                            Icon = "💼",
                            Name = "Salary",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#8BC34A",
                            Icon = "💻",
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#009688",
                            Icon = "📈",
                            Name = "Investment",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#00BCD4",
                            Icon = "💰",
                            Name = "Other Income",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FF5722",
                            Icon = "🛒",
                            Name = "Groceries",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Color = "#795548",
                            Icon = "🏠",
                            Name = "Bills",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Color = "#607D8B",
                            Icon = "🚗",
                            Name = "Transport",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Color = "#9C27B0",
                            Icon = "🎬",
                            Name = "Entertainment",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Color = "#F44336",
                            Icon = "💊",
                            Name = "Health",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = "#E91E63",
                            Icon = "👕",
                            Name = "Clothing",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Color = "#9E9E9E",
                            Icon = "📦",
                            Name = "Other Expense",
                            Type = 1
                        });
                });

            modelBuilder.Entity("PersonalFinanceTracker.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceTracker.Models.Transaction", b =>
                {
                    b.HasOne("PersonalFinanceTracker.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalFinanceTracker.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
